apiVersion: v1
kind: Secret
metadata:
  name: prod-secrets
type: Opaque
data:
  postgres-password: cHJvZC1zZWN1cmUtcGFzc3dvcmQ=  # base64 encoded password
  redis-password: cHJvZC1zZWN1cmUtcGFzc3dvcmQ=    # base64 encoded password
  jwt-secret: cHJvZC1zZWN1cmUtc2VjcmV0LWtleQ==   # base64 encoded secret key
