# Contextual Awareness Agent Configuration

# Logging settings
logging:
  level: INFO  # Options: DEBUG, INFO, WARNING, ERROR
  log_to_file: true
  log_file_path: /var/log/contextual-awareness-agent.log

# Contextual data sources
context_sources:
  - name: location_service
    endpoint: http://location-service:5008
    enabled: true
  - name: calendar_service
    endpoint: http://calendar-service:5009
    enabled: true
  - name: user_profile_service
    endpoint: http://user-profile-service:5010
    enabled: true

# Context update interval (in seconds)
context_update_interval: 60  # Update context every 60 seconds

# Context processing settings
processing:
  use_ml_models: true  # Enable or disable machine learning models for context inference
  ml_model_path: /opt/models/contextual-awareness-model.pkl
  fallback_to_rules: true  # Fallback to rule-based processing if ML model is not available

# Notification settings
notifications:
  enabled: true
  notify_via: 
    - app
    - email
  app_endpoint: http://notification-service:5011
  email_smtp_server: smtp.mailserver.com
  email_smtp_port: 587
  email_username: your-email@example.com
  email_password: your-email-password

# API settings
api:
  host: 0.0.0.0
  port: 5012
  enable_cors: true  # Enable CORS for cross-origin requests

# Security settings
security:
  jwt_secret_key: your_jwt_secret_key
  enable_https: true
  ssl_cert_file: /etc/ssl/certs/contextual-awareness-agent.crt
  ssl_key_file: /etc/ssl/private/contextual-awareness-agent.key

# External service timeouts (in seconds)
timeouts:
  default_timeout: 5  # Default timeout for HTTP requests to external services
  location_service_timeout: 3
  calendar_service_timeout: 4

# Database settings (if the agent needs to store contextual data)
database:
  type: postgres  # Options: postgres, sqlite, mysql
  host: postgres-service
  port: 5432
  username: db_user
  password: db_password
  database_name: contextual_awareness_db

# Feature toggles
features:
  enable_proactive_suggestions: true  # Enable proactive suggestions based on context
  enable_adaptive_learning: true  # Enable adaptive learning from user behavior

# Debug settings
debug:
  enabled: false
  debug_port: 5000  # Port to run the debug server, if enabled
