# Routine Detection Agent Configuration

# Logging settings
logging:
  level: INFO  # Options: DEBUG, INFO, WARNING, ERROR
  log_to_file: true
  log_file_path: /var/log/routine-detection-agent.log

# Data sources
data_sources:
  - name: user_activity_service
    endpoint: http://user-activity-service:5020
    enabled: true
  - name: calendar_service
    endpoint: http://calendar-service:5009
    enabled: true
  - name: contextual_awareness_service
    endpoint: http://contextual-awareness-service:5012
    enabled: true

# Routine detection settings
routine_detection:
  interval: 3600  # Time interval in seconds to check for routines
  min_occurrences: 3  # Minimum number of occurrences to consider a pattern a routine
  time_threshold: 15  # Time threshold in minutes for detecting similar activities
  activity_types:
    - work
    - exercise
    - leisure
    - sleep
    - travel

# Notifications settings
notifications:
  enabled: true
  notify_via: 
    - app
    - email
  app_endpoint: http://notification-service:5011
  email_smtp_server: smtp.mailserver.com
  email_smtp_port: 587
  email_username: your-email@example.com
  email_password: your-email-password

# API settings
api:
  host: 0.0.0.0
  port: 5021
  enable_cors: true  # Enable CORS for cross-origin requests

# Security settings
security:
  jwt_secret_key: your_jwt_secret_key
  enable_https: true
  ssl_cert_file: /etc/ssl/certs/routine-detection-agent.crt
  ssl_key_file: /etc/ssl/private/routine-detection-agent.key

# External service timeouts (in seconds)
timeouts:
  default_timeout: 5  # Default timeout for HTTP requests to external services
  user_activity_service_timeout: 3
  calendar_service_timeout: 4
  contextual_awareness_service_timeout: 3

# Database settings (if the agent needs to store historical data)
database:
  type: postgres  # Options: postgres, sqlite, mysql
  host: postgres-service
  port: 5432
  username: db_user
  password: db_password
  database_name: routine_detection_db

# Feature toggles
features:
  enable_adaptive_routine_detection: true  # Enable adaptive learning from user behavior
  enable_routine_suggestions: true  # Enable routine-based suggestions to users

# Debug settings
debug:
  enabled: false
  debug_port: 5020  # Port to run the debug server, if enabled
